In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

# References

- [SKTBrain/KoBERT](https://github.com/SKTBrain/KoBERT)
- [eagle705/pytorch-bert-crf-ner](https://github.com/eagle705/pytorch-bert-crf-ner/blob/master/Visualization_BERT_NER.ipynb)
- [BERT to the rescue!](https://towardsdatascience.com/bert-to-the-rescue-17671379687f)

# Load Data

In [2]:
import io

import pandas as pd
import numpy as np

import tqdm
import matplotlib.pyplot as plt
import matplotlib.font_manager as font_manager
font_dirs = ['/usr/share/fonts/truetype/nanum']
font_files = font_manager.findSystemFonts(fontpaths=font_dirs)
font_list = font_manager.createFontList(font_files)
font_manager.fontManager.ttflist.extend(font_list)
plt.rcParams['font.family'] = 'NanumGothic'

# Using SKT BERT

In [3]:
import torch
from kobert.pytorch_kobert import get_pytorch_kobert_model
from gluonnlp.data import SentencepieceTokenizer
from kobert.utils import get_tokenizer
import sentencepiece as spm

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model, vocab  = get_pytorch_kobert_model()
model.to(device)

[██████████████████████████████████████████████████]
[██████████████████████████████████████████████████]


BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(8002, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): BertLayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): BertLayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Line

In [ ]:
# Tokenized input
#text = ["누가 기침소리를 내었는가 ? 누구인가 ?"]
#tokenized_text = list(map(lambda t: sp.EncodeAsPieces(t), text))
#print(tokenized_text[0])
#indexed_tokens = list(map(vocab.to_indices, tokenized_text))
#print(indexed_tokens[0])
#reconstructed = list(map(vocab.to_tokens, indexed_tokens))
#print(reconstructed[0])

In [4]:
# Load pre-trained model tokenizer
tok_path = get_tokenizer()
print(tok_path)
sp = spm.SentencePieceProcessor()
print(sp)
sp.Load(tok_path)

# Tokenized input
#text = "[CLS] 누가 기침소리를 내었는가 ? [SEP] 누구인가 ? [SEP]"
text = "누가 기침소리를 내었는가 ? 누구인가 ?"
tokenized_text = sp.EncodeAsPieces(text)
indexed_tokens = vocab.to_indices(tokenized_text)
reconstructed = vocab.to_tokens(indexed_tokens)

print(text)
print(tokenized_text)
print(indexed_tokens)
print(reconstructed)

[██████████████████████████████████████████████████]
/root/kobert/tokenizer_78b3253a26.model
<sentencepiece.SentencePieceProcessor; proxy of <Swig Object of type 'sentencepiece::SentencePieceProcessor *' at 0x7fb95c838e40> >
누가 기침소리를 내었는가 ? 누구인가 ?
['▁누가', '▁기', '침', '소리', '를', '▁내', '었', '는', '가', '▁?', '▁누구', '인', '가', '▁?']
[1527, 1258, 7491, 6609, 6116, 1434, 6885, 5760, 5330, 633, 1528, 7119, 5330, 633]
['▁누가', '▁기', '침', '소리', '를', '▁내', '었', '는', '가', '▁?', '▁누구', '인', '가', '▁?']


In [5]:
indexed_tokens = sp.EncodeAsIds(text)
print(indexed_tokens)

[5272, 248, 1175, 4526, 12, 121, 1528, 10, 11, 4859, 2861, 24, 11, 4859]


In [6]:
# github example
input_ids = torch.LongTensor([[31, 51, 99]]).to(device)
input_mask = torch.LongTensor([[1, 1, 1]]).to(device)
token_type_ids = torch.LongTensor([[0, 0, 1]]).to(device)

all_encoder_layers, pooled_output = model(input_ids, token_type_ids, input_mask) 
# inference 시 : token tensor, segement tensor
# training 시 : token tensor, 

print(all_encoder_layers[-1][0])
print(pooled_output.shape)
print(pooled_output)

tensor([[-0.2461,  0.2428,  0.2590,  ..., -0.4861, -0.0731,  0.0756],
        [-0.2478,  0.2420,  0.2552,  ..., -0.4877, -0.0727,  0.0754],
        [-0.2472,  0.2420,  0.2561,  ..., -0.4874, -0.0733,  0.0765]],
       device='cuda:0', grad_fn=<SelectBackward>)
torch.Size([1, 768])
tensor([[-9.0314e-02, -4.4431e-02,  1.5792e-01,  3.1426e-02, -7.4218e-01,
          3.7952e-01,  8.3690e-02, -8.2061e-02,  5.9057e-02, -7.1027e-02,
         -3.6518e-01, -1.0447e-01, -9.4905e-02,  1.4371e-01, -1.0304e-02,
          4.4356e-01, -5.9710e-01,  2.8139e-03,  8.4893e-02,  8.0748e-02,
         -1.3730e-01, -2.8074e-02,  8.6585e-02, -1.0943e-01,  1.1957e-04,
          4.2622e-01, -7.0176e-01, -1.3383e-01, -8.7509e-01, -9.9335e-02,
          8.5697e-01,  5.5653e-01, -1.6640e-02, -1.1087e-01,  2.0848e-01,
          5.8470e-01, -1.1724e-02, -7.3793e-02, -4.2836e-01, -6.7545e-02,
         -7.8296e-02, -6.5179e-02, -5.5545e-02,  6.5026e-01, -9.8818e-01,
          6.5573e-02, -1.5565e-01, -4.3171e-02, -9.8

In [7]:
# github example
input_ids = torch.LongTensor([[31, 51, 99]]).to(device)
input_mask = torch.LongTensor([[1, 1, 1]]).to(device)
token_type_ids = torch.LongTensor([[0, 0, 1]]).to(device)

all_encoder_layers, pooled_output = model(input_ids, token_type_ids)

print(all_encoder_layers[-1][0])
print(pooled_output.shape)
print(pooled_output)

tensor([[-0.2461,  0.2428,  0.2590,  ..., -0.4861, -0.0731,  0.0756],
        [-0.2478,  0.2420,  0.2552,  ..., -0.4877, -0.0727,  0.0754],
        [-0.2472,  0.2420,  0.2561,  ..., -0.4874, -0.0733,  0.0765]],
       device='cuda:0', grad_fn=<SelectBackward>)
torch.Size([1, 768])
tensor([[-9.0314e-02, -4.4431e-02,  1.5792e-01,  3.1426e-02, -7.4218e-01,
          3.7952e-01,  8.3690e-02, -8.2061e-02,  5.9057e-02, -7.1027e-02,
         -3.6518e-01, -1.0447e-01, -9.4905e-02,  1.4371e-01, -1.0304e-02,
          4.4356e-01, -5.9710e-01,  2.8139e-03,  8.4893e-02,  8.0748e-02,
         -1.3730e-01, -2.8074e-02,  8.6585e-02, -1.0943e-01,  1.1957e-04,
          4.2622e-01, -7.0176e-01, -1.3383e-01, -8.7509e-01, -9.9335e-02,
          8.5697e-01,  5.5653e-01, -1.6640e-02, -1.1087e-01,  2.0848e-01,
          5.8470e-01, -1.1724e-02, -7.3793e-02, -4.2836e-01, -6.7545e-02,
         -7.8296e-02, -6.5179e-02, -5.5545e-02,  6.5026e-01, -9.8818e-01,
          6.5573e-02, -1.5565e-01, -4.3171e-02, -9.8